# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fab90c5cde6494e01e78f201bcc4d5b47dd54dfe108ad88305b29fdf42599714a2fba0b1a77a718f64336169b68e865441e7c764bad408d8c2c0bd12a20b0d48

test:
  secret_key_base: 54ffe0d68d4cd01607b9b04974af9ce435d93151d6d492c18d228c79898366fe35b1ffffa4ff47008ddc6f9c1733327bd74fe330476179598f14e7ef0f71f202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
